/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\scene.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Scene(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig" position={[0, 0.069, 0]} scale={3.269}>
          <primitive object={nodes.spine003} />
          <primitive object={nodes.spine007} />
          <skinnedMesh name="FinalBaseMesh" geometry={nodes.FinalBaseMesh.geometry} material={materials['MATERIAL DEFINITIVO']} skeleton={nodes.FinalBaseMesh.skeleton} />
        </group>
        <group name="Vacío" position={[0, 0.893, 0]} />
        <mesh name="BASE_ESTATUA" geometry={nodes.BASE_ESTATUA.geometry} material={materials['MATERIAL DEFINITIVO']} position={[0, 0.893, 0]} scale={[1.652, 0.534, 1]} />
        <mesh name="ESFERA_EMISION" geometry={nodes.ESFERA_EMISION.geometry} material={materials['Material.001']} position={[2.458, 6.874, 0.704]} scale={0.215} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
